version: '3.4'

services:
  bucketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  discountapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  discountgrpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

