version: '3.4'

services:
  catalogdb:
    container_name : catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bucketdb:
    container_name: bucketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=unclejo
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
       - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
       SA_PASSWORD: "Unclejo007!"
       ACCEPT_EULA: "Y"
       hostname : OnDocker 
    restart: always
    ports:
       - "1434:1433"
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=unclejo
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogapi:
    container_name : catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"


    depends_on:
      - catalogdb    
    ports:
      - "8000:80"
  bucketapi:

    container_name: bucketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=bucketdb:6379"
    
    depends_on:
      - bucketdb
    ports:
       - "8001:80"


  discountapi:
    container_name: discountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=unclejo;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- "ConnectionStrings:OrderingConnectionString=Server=localhost,1434,Database=OrderDb;User Id=SA;Password=Unclejo007!;TrustServerCertificate=True"
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Unclejo007!"  

    depends_on:
        - orderdb
       
    ports:
        - "8004:80"

