version: '3.4'

services:
  bucketapi:
    image: ${DOCKER_REGISTRY-}bucketapi
    build:
      context: .
      dockerfile: Services/Bucket/BucketAPI/Dockerfile

  discountapi:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/DiscountAPI/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile


  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/DiscountGRPC/Dockerfile


  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

