version: '3.4'

services:
  catalogdb:
    image: mongo
  bucketdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services\Catalog\CatalogAPI\Dockerfile
  bucketapi:
    image: ${DOCKER_REGISTRY-}bucketapi
    build:
      context: .
      dockerfile: Services/Bucket/BucketAPI/Dockerfile

volumes:
  mongo_data:
  portainer_data:
